name: review_service
description: A multi-platform recipe to rate mobile apps.
version: 0.1.0+1
homepage: https://github.com/nventive/ReviewService-Dart

environment:
  sdk: "^3.3.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  in_app_review: ^2.0.9
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
